{{- if and (not .Values.api.existingSecret) .Values.api.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mutx.fullname" . }}-api-env
  labels:
    {{- include "mutx.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
stringData:
  {{- range $name, $value := .Values.api.secretEnv }}
  {{ $name }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
{{- if and (not .Values.frontend.existingSecret) .Values.frontend.secretEnv }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mutx.fullname" . }}-frontend-env
  labels:
    {{- include "mutx.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
type: Opaque
stringData:
  {{- range $name, $value := .Values.frontend.secretEnv }}
  {{ $name }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
